### ISSUE TITLE
[Bug] Nil pointer dereference related to excludedPrefixes

### ISSUE THREAD

**Issue by bartsmykla** [networkservicemesh/networkservicemesh#1007]
## Expected Behavior
Not crashing :-)

## Current Behavior
`nsmgr/nsmd` crashing after installation of example (ie. `imcp-responder`)

## Steps to Reproduce

1. Installing nsm using helm:
```
helm install --name nsm ./deployments/helm/nsm
```
2. Installing `icmp-responder` example via helm:
```
helm install ./deployments/helm/icmp-responder --name icmp-responder 
```
3. Crash inside network service mesh manager, container: `nsmd` (nil pointer dereference panic)

## Context

* Kubernetes Version: 1.14.1
* etc.

## Failure Logs
Logs of `nsmd`:
```
goroutine 614 [running]:
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).updateExcludePrefixes(0xc000060240, 0xb990e0, 0xc00053e000)
	/root/networkservicemesh/controlplane/pkg/nsm/nsm.go:637 +0x347
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).findConnectNSE(0xc000060240, 0xc000398e08, 0x8, 0xb920e0, 0xc0001d8c30, 0xc000131678, 0xb93820, 0xc0002d0940, 0xb990e0, 0xc00053e240, ...)
	/root/networkservicemesh/controlplane/pkg/nsm/nsm.go:359 +0x155
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).request(0xc000060240, 0xb920e0, 0xc0001d8c30, 0xb93820, 0xc0002d0940, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/networkservicemesh/controlplane/pkg/nsm/nsm.go:209 +0x736
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).Request(0xc000060240, 0xb920e0, 0xc0001d8c30, 0xb93820, 0xc0002d0940, 0x1, 0x1, 0x409c03, 0xa0cea0)
	/root/networkservicemesh/controlplane/pkg/nsm/nsm.go:93 +0x92
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsmd.(*networkServiceServer).Request(0xc0000a6a80, 0xb920e0, 0xc0001d8c30, 0xc0002d0940, 0xc0000a6a80, 0x0, 0x0)
	/root/networkservicemesh/controlplane/pkg/nsmd/network_service_server.go:43 +0xef
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/apis/local/networkservice._NetworkService_Request_Handler.func1(0xb920e0, 0xc0001d8c30, 0xa89760, 0xc0002d0940, 0xa9bf20, 0xc0001792c0, 0xb920e0, 0xc0001d8c30)
	/root/networkservicemesh/controlplane/pkg/apis/local/networkservice/networkservice.pb.go:143 +0x86
github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0xb920e0, 0xc0001d8a80, 0xa89760, 0xc0002d0940, 0xc00029d780, 0xc00029d7a0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e4
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/apis/local/networkservice._NetworkService_Request_Handler(0xa11460, 0xc0000a6a80, 0xb920e0, 0xc0001d8a80, 0xc000325ef0, 0xc000446b20, 0xb920e0, 0xc0001d8a80, 0xc0002b80a0, 0x92)
	/root/networkservicemesh/controlplane/pkg/apis/local/networkservice/networkservice.pb.go:145 +0x158
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00028c900, 0xb982e0, 0xc000127380, 0xc000354500, 0xc0002cebd0, 0xffe560, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.20.1/server.go:972 +0x470
google.golang.org/grpc.(*Server).handleStream(0xc00028c900, 0xb982e0, 0xc000127380, 0xc000354500, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.20.1/server.go:1252 +0xda6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00002b600, 0xc00028c900, 0xb982e0, 0xc000127380, 0xc000354500)
	/go/pkg/mod/google.golang.org/grpc@v1.20.1/server.go:691 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.20.1/server.go:689 +0xa1
```

**Comment by nickolaev** [comment]
#1008 merged. Closing.
