### ISSUE TITLE
nsmd crash in findConnectNSE

### ISSUE THREAD

**Issue by nickolaev** [networkservicemesh/networkservicemesh#1132]
## Expected Behavior

nsmd should not crash

## Current Behavior

`nil` pointer dereference crash

## Failure Information (for bugs)

``` shell
time="2019-05-18T05:38:36Z" level=info msg="Selecting endpoint for icmp-responder with 1 matches."
time="2019-05-18T05:38:36Z" level=info msg="Matching ednpoint for labels map[:]"
time="2019-05-18T05:38:36Z" level=info msg="Create remote NSE connection to endpoint: <nil>"
time="2019-05-18T05:38:36Z" level=info msg="Waiting for liveness probe: tcp:"
time="2019-05-18T05:38:46Z" level=error msg="NSM:(7.1.8-64F1948A) NSE respond with error: NSM:(7.2.6.1) Failed to create NSE Client. timeout waiting for: tcp: "
2019/05/18 05:38:46 Reporting span 3bb81047999ac92e:75c0c39911ca6daf:3bb81047999ac92e:1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x955740]

goroutine 59 [running]:
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).findConnectNSE(0xc000180600, 0xc00002a5b8, 0x8, 0xb97460, 0xc00013e240, 0xc00002c060, 0xb98c20, 0xc00014c240, 0xb9e540, 0xc0003e0660, ...)
	/root/networkservicemesh/controlplane/pkg/nsm/nsm.go:392 +0x2e0
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).request(0xc000180600, 0xb97460, 0xc00013e240, 0xb98c20, 0xc00014c240, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/networkservicemesh/controlplane/pkg/nsm/nsm.go:233 +0x6d1
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).Request(0xc000180600, 0xb97460, 0xc00013e240, 0xb98c20, 0xc00014c240, 0x1, 0x1, 0x409c03, 0xa108a0)
	/root/networkservicemesh/controlplane/pkg/nsm/nsm.go:117 +0x92
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsmd.(*networkServiceServer).Request(0xc00005cf40, 0xb97460, 0xc00013e240, 0xc00014c240, 0xc00005cf40, 0x0, 0x0)
	/root/networkservicemesh/controlplane/pkg/nsmd/network_service_server.go:44 +0xef
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/apis/local/networkservice._NetworkService_Request_Handler.func1(0xb97460, 0xc00013e240, 0xa8e160, 0xc00014c240, 0xaa0740, 0xc000216000, 0xb97460, 0xc00013e240)
	/root/networkservicemesh/controlplane/pkg/apis/local/networkservice/networkservice.pb.go:143 +0x86
github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0xb97460, 0xc00013e090, 0xa8e160, 0xc00014c240, 0xc000148240, 0xc000148260, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e4
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/apis/local/networkservice._NetworkService_Request_Handler(0xa151e0, 0xc00005cf40, 0xb97460, 0xc00013e090, 0xc00014a230, 0xc00000cec0, 0xb97460, 0xc00013e090, 0xc0002ba120, 0x8b)
	/root/networkservicemesh/controlplane/pkg/apis/local/networkservice/networkservice.pb.go:145 +0x158
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003a2180, 0xb9d740, 0xc0003a2f00, 0xc000294000, 0xc00002d320, 0x10085a0, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.20.1/server.go:972 +0x470
google.golang.org/grpc.(*Server).handleStream(0xc0003a2180, 0xb9d740, 0xc0003a2f00, 0xc000294000, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.20.1/server.go:1252 +0xda6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00002a690, 0xc0003a2180, 0xb9d740, 0xc0003a2f00, 0xc000294000)
	/go/pkg/mod/google.golang.org/grpc@v1.20.1/server.go:691 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.20.1/server.go:689 +0xa1
```

## Steps to Reproduce

Deploy a Network Service resource (like secure-intranet-connectivity.yaml)
Deploy the client that requests the service, before the endpoint itself.
The following code does not handle the `endpoint` is `nil` behaviour:
```go
func (srv *networkServiceManager) findConnectNSE ... {
....
	for {
	...
		// 7.1.3 Check if endpoint is not ignored yet

		if endpoint == nil {
			// 7.1.4 Choose a new endpoint
			endpoint, err = srv.nseManager.getEndpoint(ctx, nseConnection, ignore_endpoints)
		}
		....

		// 7.1.7 perform request to NSE/remote NSMD/NSE
		clientConnection, err = srv.performNSERequest(requestId, ctx, endpoint, nseConnection, request, dp, existingConnection)

		// 7.1.8 in case of error we put NSE into ignored list to check another one.
		if err != nil {
			logrus.Errorf("NSM:(7.1.8-%v) NSE respond with error: %v ", requestId, err)
			last_error = err
			ignore_endpoints[endpoint.NetworkserviceEndpoint.EndpointName] = endpoint
			continue
		}
		// 7.1.9 We are fine with NSE connection and could continue.
		return clientConnection, nil
	}
}
```

In `7.1.4` one still may get a nil endpoint, which later gets derefenrenced whe indexing the `ignore_endpoints` in `ignore_endpoints[endpoint.NetworkserviceEndpoint.EndpointName] = endpoint`.

The fillowing patch seems to fix the immediate crash but does not necesarrily fix the issue properly:
```diff
diff --git a/controlplane/pkg/nsm/nsm.go b/controlplane/pkg/nsm/nsm.go
index 92d5e7c7..5ec08ab2 100644
--- a/controlplane/pkg/nsm/nsm.go
+++ b/controlplane/pkg/nsm/nsm.go
@@ -389,7 +389,9 @@ func (srv *networkServiceManager) findConnectNSE(requestId string, ctx context.C
                if err != nil {
                        logrus.Errorf("NSM:(7.1.8-%v) NSE respond with error: %v ", requestId, err)
                        last_error = err
-                       ignore_endpoints[endpoint.NetworkserviceEndpoint.EndpointName] = endpoint
+                       if endpoint != nil {
+                               ignore_endpoints[endpoint.NetworkserviceEndpoint.EndpointName] = endpoint
+                       }
                        continue
                }
                // 7.1.9 We are fine with NSE connection and could continue.
```

**Comment by nickolaev** [comment]
@haiodo please check if this makes sense.

**Comment by lobkovilya** [comment]
@nickolaev looks like the problem starts at `getEndpoints(...)` method:
```go
endpointResponse, err := discoveryClient.FindNetworkService(ctx, nseRequest)
if err != nil {
	logrus.Error(err)
	return nil, err
}
endpoints := filterEndpoints(endpointResponse.GetNetworkServiceEndpoints(), ignore_endpoints)

if len(endpoints) == 0 {
	return nil, fmt.Errorf("Failed to find NSE for NetworkService %s. Checked: %d of total NSEs: %d",
		requestConnection.GetNetworkService(), len(ignore_endpoints), len(endpoints))
}

endpoint := nsem.model.GetSelector().SelectEndpoint(requestConnection.(*local_connection.Connection), endpointResponse.GetNetworkService(), endpoints)
if endpoint == nil {
	return nil, err
}
```

If `FindNetworkService` returns non-empty endpoint list, but `SelectEndpoints` returns `nil` we return `nil, err`. But `err` in that case is also nil. That's why the next error check in `findConnectEndpoint` will success:
```go
if endpoint == nil {
	// 7.1.4 Choose a new endpoint
	endpoint, err = srv.nseManager.getEndpoint(ctx, nseConnection, ignore_endpoints)
}
if err != nil {
	// 7.1.5 No endpoints found, we need to return error, including last error for previous NSE
	if last_error != nil {
		return nil, fmt.Errorf("NSM:(7.1.5-%v) %v. Last NSE Error: %v", requestId, err, last_error)
	} else {
		return nil, err
	}
}
``` 
and we will get nil pointer crush.

**Comment by lobkovilya** [comment]
Also according to logs that you attached:
```
time="2019-05-18T05:38:36Z" level=info msg="Matching ednpoint for labels map[:]"
```
labels of NSC is empty, probably that's why `SelectEndpoint` returns nil

**Comment by edwarnicke** [comment]
@lobkovilya could this also be related to #1130 ?

If so, would be super useful to get a fix sooner rather than later, for kubecon demo purposes :)

**Comment by lobkovilya** [comment]
@edwarnicke #1130 very similar stack trace and it's really seems like the bugs have one root cause. But unfortunately I haven't had a chance to reproduce the problem to be sure that fix will help. But #1134 it is very likely fixes the problem mentioned above in that issue

**Comment by nickolaev** [comment]
The crash is solved in the latest master, but the service does not get connected. I will close this one and open a new explaining how to reproduce it.
