### ISSUE TITLE
CloudTest could crash

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#1341]
## Expected Behavior

CloudTest should execute tests.

## Current Behavior

It could fail if Packet response with error:

## Failure Information (for bugs)

```
INFO[0057] packet-1-Checking status Worker bfae2e42-bbbe-47d4-bdf8-6671a04611a9 provisioning 
ERRO[0059] Error GET https://api.packet.net/devices/1e611e49-0c6a-430b-9ba6-f297c70e53ae?include=facility: 403 You are not authorized to view this device  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x10bacf3]

goroutine 35 [running]:
github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/providers/packet.(*packetInstance).waitDevicesStartup(0xc000233040, 0x1571040, 0xc0002fa420, 0x0, 0x0)
	/home/circleci/project/test/cloudtest/pkg/providers/packet/packet_provider.go:252 +0x1d3
github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/providers/packet.(*packetInstance).Start(0xc000233040, 0x8bb2c97000, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/test/cloudtest/pkg/providers/packet/packet_provider.go:162 +0x713
github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/commands.(*executionContext).startCluster.func1(0xc000214c00, 0xc000259b00, 0xc0003140a0)
	/home/circleci/project/test/cloudtest/pkg/commands/main.go:700 +0x71
created by github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/commands.(*executionContext).startCluster
	/home/circleci/project/test/cloudtest/pkg/commands/main.go:696 +0x15a
Exited with code 2
```
## Steps to Reproduce

1. Step 1
2. Step 2
3. You get the idea...

## Context

* Kubernetes Version:
* etc.

**Comment by haiodo** [comment]
This one is resolved.
