### ISSUE TITLE
TestTransferBetweenMemifProxies fails on CI

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#1353]
## Expected Behavior

TestTransferBetweenMemifProxies test should pass.

## Current Behavior

TestTransferBetweenMemifProxies is failed.

## Failure Information (for bugs)

```
=== RUN   TestTransferBetweenMemifProxies
time="2019-07-15T17:50:48Z" level=info msg="Request proxy source: source.sock, target: target.sock"
time="2019-07-15T17:50:48Z" level=info msg="Resolved source socket unix address: source.sock"
time="2019-07-15T17:50:48Z" level=info msg="Resolved target socket unix address: target.sock"
time="2019-07-15T17:50:48Z" level=info msg="Request proxy source: target.sock, target: source.sock"
time="2019-07-15T17:50:48Z" level=info msg="Resolved source socket unix address: target.sock"
time="2019-07-15T17:50:48Z" level=info msg="Resolved target socket unix address: source.sock"
--- FAIL: TestTransferBetweenMemifProxies (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5501dd]

goroutine 16 [running]:
testing.tRunner.func1(0xc00013c200)
	/usr/local/go/src/testing/testing.go:830 +0x392
panic(0x582c40, 0x79e320)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/networkservicemesh/networkservicemesh/dataplane/pkg/tests.connectAndSendMsg(0x5bd5de, 0xb)
	/go/src/github.com/networkservicemesh/networkservicemesh/dataplane/pkg/tests/memif_proxy_test.go:53 +0x1dd
github.com/networkservicemesh/networkservicemesh/dataplane/pkg/tests.TestTransferBetweenMemifProxies(0xc00013c200)
	/go/src/github.com/networkservicemesh/networkservicemesh/dataplane/pkg/tests/memif_proxy_test.go:31 +0x171
testing.tRunner(0xc00013c200, 0x5cae98)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
FAIL	github.com/networkservicemesh/networkservicemesh/dataplane/pkg/tests	0.248s
```
## Steps to Reproduce

Failed on CI.

**Comment by denis-tingajkin** [comment]
@edwarnicke can we close this issue too?
