### ISSUE TITLE
CloudTest is failed because of error

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#1435]
## Expected Behavior

CloudTest should not fail

## Current Behavior

It fail

## Failure Information (for bugs)

```
ERRO[3791] Failed to create ssh key POST https://api.packet.net/projects/383890d0-f5d1-4de1-881a-4d1ede549d18/ssh-keys: 422 Key already exists  
INFO[3791] Destroying cluster  packet-1                 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10cff20]

goroutine 5231 [running]:
github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/providers/packet.(*packetInstance).Destroy(0xc000234ea0, 0x8bb2c97000, 0x8bb2c97000, 0x3ebc)
	/home/circleci/project/test/cloudtest/pkg/providers/packet/packet_provider.go:372 +0xf0
github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/commands.(*executionContext).destroyCluster(0xc000116c00, 0xc00025f900, 0x1)
	/home/circleci/project/test/cloudtest/pkg/commands/main.go:796 +0xf0
github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/commands.(*executionContext).startCluster.func1(0xc000116c00, 0xc00025f900, 0xc0004860f0)
	/home/circleci/project/test/cloudtest/pkg/commands/main.go:708 +0xe0
created by github.com/networkservicemesh/networkservicemesh/test/cloudtest/pkg/commands.(*executionContext).startCluster
	/home/circleci/project/test/cloudtest/pkg/commands/main.go:699 +0x16b
Exited with code 2
```
## Context

* Kubernetes Version:
* etc.

**Comment by haiodo** [comment]
Changes merged.
