### ISSUE TITLE
Fuzzing bug: panic in parseProcFile

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/networkservicemesh#1614]
## Expected Behavior

NSM components should survive fuzzying

## Current Behavior

time="2019-09-14T03:09:43-04:00" level=error msg="Failed to read routes files: EOF"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/networkservicemesh/networkservicemesh/dataplane/pkg/common.parseProcFile(0xc000070180, 0xc00012a420, 0x1000, 0xc000070180, 0x4751f6, 0x5d7c9237, 0x113e56dd, 0xcb4da9fb5d7)
	/home/user/go/src/github.com/networkservicemesh/networkservicemesh/dataplane/pkg/common/egress_interface.go:82 +0x736
github.com/networkservicemesh/networkservicemesh/dataplane/pkg/common.FuzzParseProcFile(0x7796ee36d000, 0x1, 0x1, 0x3)
	/home/user/go/src/github.com/networkservicemesh/networkservicemesh/dataplane/pkg/common/egress_interface_fuzz.go:13 +0xe3
go-fuzz-dep.Main(0xc000135f80, 0x1, 0x1)
	/tmp/go-fuzz-build282549799/goroot/src/go-fuzz-dep/main.go:36 +0x1b6
main.main()
	/tmp/go-fuzz-build282549799/gopath/src/github.com/networkservicemesh/networkservicemesh/dataplane/pkg/common/go.fuzz.main/main.go:15 +0x52

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
	/tmp/go-fuzz-build282549799/goroot/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/share/go/src/os/signal/signal_unix.go:23 +0x52
created by os/signal.init.0
	/usr/share/go/src/os/signal/signal_unix.go:29 +0x41
exit status 2

## References

#1518 
[crashers.ProcFile.zip](https://github.com/networkservicemesh/networkservicemesh/files/3612440/crashers.ProcFile.zip)

**Comment by bookmoons** [comment]
[`parse-proc-crash`](https://github.com/bookmoons/networkservicemesh/tree/parse-proc-crash) add a unit test for this case.
