### ISSUE TITLE
Invalid memory address or nil pointer dereference on networkServiceManager.getEndpoint()

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#1914]
## Steps to Reproduce
Run chain of the tests:
1) TestVPNLocal
2) TestSeveralCrossConnects

Actual: nsmd has a runtime error.

Note: use one instance of nsmgr and forwarder for each test

## Build

https://circleci.com/gh/networkservicemesh/networkservicemesh/115872#artifacts/containers/0

## Failure Logs
```
time="2019-11-19T17:48:51Z" level=info msg="Requesting NetworkServiceDiscoveryClient..."
time="2019-11-19T17:48:51Z" level=info msg="==--------> getEndpoint() span:{}"
time="2019-11-19T17:48:51Z" level=info msg="Discovering endpoint at registry Network service: secure-intranet-connectivity endpoint: secure-intranet-connectivitymbkxd " operation=getEndpoint span="{}"
time="2019-11-19T17:48:51Z" level=info msg=">><<---------- /registry.NetworkServiceDiscovery/FindNetworkService()=\"\" span={}"
time="2019-11-19T17:48:51Z" level=info msg=">><<---------- request={\"network_service_name\":\"secure-intranet-connectivity\"} span={}"
time="2019-11-19T17:48:51Z" level=info msg=">><<---------- response={} span={}"
time="2019-11-19T17:48:51Z" level=error msg=">><<-------- error=rpc error: code = Unknown desc = no NetworkService with name: secure-intranet-connectivity span={}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9703d5]

goroutine 62 [running]:
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).getEndpoint(0xc0002281e0, 0xbfd6c0, 0xc0000f55f0, 0xc00025eb60, 0x1c, 0xc000300030, 0x21, 0xbee900, 0xc000176538, 0xc00009cfa0, ...)
	/home/circleci/project/controlplane/pkg/nsm/nsm.go:328 +0x305
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).findEndpoint(0xc0002281e0, 0xbfd6c0, 0xc0000f55f0, 0xc000300030, 0x21, 0xc00025eb60, 0x1c, 0xbee900, 0xc000176538, 0xc00009cfa0, ...)
	/home/circleci/project/controlplane/pkg/nsm/nsm.go:246 +0xdd
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).restoreXconnection(0xc0002281e0, 0xbfd6c0, 0xc0000f53b0, 0xc00009cfa0, 0xc06940, 0xc0001de0e0, 0xc000180570, 0x8, 0x7f223aea4360, 0xc0000a94a0)
	/home/circleci/project/controlplane/pkg/nsm/nsm.go:212 +0x545
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).RestoreConnections(0xc0002281e0, 0xc000285e00, 0x4, 0x4, 0xc000180570, 0x8, 0x7f223aea4360, 0xc0000a94a0)
	/home/circleci/project/controlplane/pkg/nsm/nsm.go:180 +0x181
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/services.(*ClientConnectionManager).UpdateFromInitialState(...)
	/home/circleci/project/controlplane/pkg/services/client_connection_manager.go:382
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsmd.(*NsmMonitorCrossConnectClient).handleXconEvent(0xc000200820, 0xbfd900, 0xc00007a6c0, 0xc000386d80, 0x0, 0x104b170, 0xc0001e2900)
	/home/circleci/project/controlplane/pkg/nsmd/nsmd_crossconnect_client.go:425 +0x27d
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsmd.(*NsmMonitorCrossConnectClient).forwarderCrossConnectMonitor.func2(0xbfd900, 0xc00007a6c0, 0x0, 0x16, 0x0)
	/home/circleci/project/controlplane/pkg/nsmd/nsmd_crossconnect_client.go:362 +0x51
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsmd.(*NsmMonitorCrossConnectClient).monitor(0xc000200820, 0xbfd6c0, 0xc000251500, 0xb246f8, 0x1c, 0xb278ec, 0x20, 0xc000180570, 0x8, 0xc00019df90, ...)
	/home/circleci/project/controlplane/pkg/nsmd/nsmd_crossconnect_client.go:275 +0x7c0
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsmd.(*NsmMonitorCrossConnectClient).forwarderCrossConnectMonitor(0xc000200820, 0xbfd600, 0xc00007a8c0, 0xc000386d80)
	/home/circleci/project/controlplane/pkg/nsmd/nsmd_crossconnect_client.go:365 +0x2e5
created by github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsmd.(*NsmMonitorCrossConnectClient).ForwarderAdded
	/home/circleci/project/controlplane/pkg/nsmd/nsmd_crossconnect_client.go:126 +0x194
```

**Comment by denis-tingajkin** [comment]
looks like fixed
