### ISSUE TITLE
TestUpdateConnectionOnNSEChange can fail because of nil pointer on update connection

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/networkservicemesh#2125]
## Expected Behavior

TestUpdateConnectionOnNSEChange  is stable on CI

## Current Behavior

TestUpdateConnectionOnNSEChange is not stable on CI

## Failure Information (for bugs)

```
goroutine 33 [running]:
github.com/networkservicemesh/networkservicemesh/side-cars/pkg/nsm-monitor.(*nsmMonitorApp).updateConnection(0xc0000f2960, 0xc0000da000)
	/home/circleci/project/side-cars/pkg/nsm-monitor/nsm-monitor.go:200 +0x1a8
github.com/networkservicemesh/networkservicemesh/side-cars/pkg/nsm-monitor.(*nsmMonitorApp).readEvents(0xc0000f2960, 0xa97180, 0xc000114280, 0xc00007c401)
	/home/circleci/project/side-cars/pkg/nsm-monitor/nsm-monitor.go:186 +0x2db
github.com/networkservicemesh/networkservicemesh/side-cars/pkg/nsm-monitor.(*nsmMonitorApp).beginMonitoring(0xc0000f2960)
	/home/circleci/project/side-cars/pkg/nsm-monitor/nsm-monitor.go:157 +0x449
created by github.com/networkservicemesh/networkservicemesh/side-cars/pkg/nsm-monitor.(*nsmMonitorApp).Run
	/home/circleci/project/side-cars/pkg/nsm-monitor/nsm-monitor.go:104 +0x96
```

## Build

https://circleci.com/gh/networkservicemesh/networkservicemesh/121563

## Containers logs

[TestUpdateConnectionOnNSEChange.zip](https://github.com/networkservicemesh/networkservicemesh/files/4316375/TestUpdateConnectionOnNSEChange.zip)

**Comment by denis-tingajkin** [comment]
Fixed by https://github.com/networkservicemesh/networkservicemesh/pull/2124
