### ISSUE TITLE
VPP Agent Dataplane filed to start inside GKE

### ISSUE THREAD

**Issue by haiodo** [networkservicemesh/networkservicemesh#849]
## Expected Behavior

VPP Dataplane is not starting inside GKE

## Current Behavior

VPP Agent dataplane could not start since VPP agent is crashing.

## Steps to Reproduce

1. Build and deploy latest to GKE.
2. Create yaml descr
```
---
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: just-vpp
    spec:
      containers:
        - name: alpine-img
          securityContext:
            privileged: true
          image: networkservicemesh/vppagent-dataplane:latest
          command: ['tail', '-f', '/dev/null']
metadata:
  name: just-vpp
  namespace: default
```
3. Deploy into GKE.
4. ` /usr/bin/vpp -c /etc/vpp/vpp.conf &> vpp.log &`
5. `/usr/bin/exec_agent.sh `

## Context

* Kubernetes Version:
* etc.

## Failure Logs

```
root@alphine-799df4b7cc-sxwn5:~# cat vpp.log 
vlib_plugin_early_init:361: plugin path /usr/lib/vpp_plugins
load_one_plugin:189: Loaded plugin: abf_plugin.so (ACL based Forwarding)
load_one_plugin:189: Loaded plugin: acl_plugin.so (Access Control Lists)
load_one_plugin:189: Loaded plugin: avf_plugin.so (Intel Adaptive Virtual Function (AVF) Device Plugin)
load_one_plugin:191: Loaded plugin: cdp_plugin.so
load_one_plugin:106: Plugin disabled: dpdk_plugin.so
load_one_plugin:189: Loaded plugin: flowprobe_plugin.so (Flow per Packet)
load_one_plugin:189: Loaded plugin: gbp_plugin.so (Group Based Policy)
load_one_plugin:189: Loaded plugin: gtpu_plugin.so (GTPv1-U)
load_one_plugin:189: Loaded plugin: igmp_plugin.so (IGMP messaging)
load_one_plugin:189: Loaded plugin: ila_plugin.so (Identifier-locator addressing for IPv6)
load_one_plugin:189: Loaded plugin: ioam_plugin.so (Inbound OAM)
load_one_plugin:117: Plugin disabled (default): ixge_plugin.so
load_one_plugin:189: Loaded plugin: l2e_plugin.so (L2 Emulation)
load_one_plugin:189: Loaded plugin: lacp_plugin.so (Link Aggregation Control Protocol)
load_one_plugin:189: Loaded plugin: lb_plugin.so (Load Balancer)
load_one_plugin:189: Loaded plugin: mactime_plugin.so (Time-based MAC source-address filter)
load_one_plugin:189: Loaded plugin: map_plugin.so (Mapping of address and port (MAP))
load_one_plugin:189: Loaded plugin: memif_plugin.so (Packet Memory Interface (experimental))
load_one_plugin:189: Loaded plugin: nat_plugin.so (Network Address Translation)
load_one_plugin:189: Loaded plugin: nsh_plugin.so (Network Service Header)
load_one_plugin:189: Loaded plugin: nsim_plugin.so (network delay simulator plugin)
load_one_plugin:189: Loaded plugin: perfmon_plugin.so (Performance monitor plugin)
load_one_plugin:189: Loaded plugin: pppoe_plugin.so (PPPoE)
load_one_plugin:189: Loaded plugin: srv6ad_plugin.so (Dynamic SRv6 proxy)
load_one_plugin:189: Loaded plugin: srv6am_plugin.so (Masquerading SRv6 proxy)
load_one_plugin:189: Loaded plugin: srv6as_plugin.so (Static SRv6 proxy)
load_one_plugin:189: Loaded plugin: stn_plugin.so (VPP Steals the NIC for Container integration)
load_one_plugin:189: Loaded plugin: svs_plugin.so (Source VRF Select)
load_one_plugin:189: Loaded plugin: tlsmbedtls_plugin.so (mbedtls based TLS Engine)
load_one_plugin:189: Loaded plugin: tlsopenssl_plugin.so (openssl based TLS Engine)
load_one_plugin:117: Plugin disabled (default): unittest_plugin.so
load_one_plugin:189: Loaded plugin: vmxnet3_plugin.so (VMWare Vmxnet3 Device Plugin)
/usr/bin/vpp[54]: clib_elf_parse_file: open `linux-vdso.so.1': No such file or directory
/usr/bin/vpp[54]: clib_sysfs_prealloc_hugepages:261: pre-allocating 7 additional 2048K hugepages on numa node 0
/usr/bin/vpp[54]: buffer: vlib_physmem_shared_map_create: pmalloc_map_pages: failed to mmap 7 pages at 0x1000000000 fd 4 numa 0 flags 0x2011: Cannot allocate memory

/usr/bin/vpp[54]: buffer: falling back to non-hugepage backed buffer pool
/usr/bin/vpp[54]: perfmon: Failed to read CPU-specific counter table /usr/share/vpp/plugins/perfmon/skylakex_core_v1.12.json
/usr/bin/vpp[54]: perfmon: Please install the vpp-dev package and then:
/usr/bin/vpp[54]: perfmon: cd /usr/share/vpp/plugins/perfmon; sudo tar Jxf PerfmonTables.tar.xz
/usr/bin/vpp[54]: perfmon: and restart vpp.
/usr/bin/vpp[54]: unix_proc_file_contents: open `/usr/share/vpp/plugins/perfmon/skylakex_core_v1.12.json': No such file or directory
/usr/bin/vpp[54]: perfmon: No table for cpuid 50653
/usr/bin/vpp[54]: perfmon:   model 55, stepping 3
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: memif_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: acl_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: mactime_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: avf_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: nat_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: dpdk_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: nsh_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: gtpu_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: flowprobe_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: pppoe_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: lb_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: nsim_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: cdp_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: ioam_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: stn_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: lacp_test_plugin.so
/usr/bin/vpp[54]: load_one_vat_plugin:67: Loaded plugin: vmxnet3_test_plugin.so
root@alphine-799df4b7cc-sxwn5:~# cat agent.log.log 
cat: agent.log.log: No such file or directory
root@alphine-799df4b7cc-sxwn5:~# cat agent.log     
Starting vpp-agent..
time="2019-03-15 17:27:15.92334" level=debug msg="using plugin logger for \"vpp-grpc\" that was already initialized" loc="logging/log_api.go(176)" logger=defaultLogger
time="2019-03-15 17:27:15.92399" level=info msg="Starting agent version: v1.8.1" BuildDate="2019-03-04T11:08-08:00" CommitHash=905b269cfd7de48874f093c73fc691ea29ead3c1 loc="agent/agent.go(129)" logger=agent
time="2019-03-15 17:27:16.02242" level=info msg="Starting agent with 25 plugins" loc="agent/agent.go(199)" logger=agent
time="2019-03-15 17:27:16.02256" level=debug msg="Microservice label is set to vpp1" loc="servicelabel/plugin_impl_servicelabel.go(44)" logger=defaultLogger
time="2019-03-15 17:27:16.02276" level=info msg="Consul config not found, skip loading this plugin" loc="consul/plugin.go(137)" logger=consul
time="2019-03-15 17:27:16.02283" level=info msg="Redis config not found, skip loading this plugin" loc="redis/plugin_impl_redis.go(123)" logger=redis
time="2019-03-15 17:27:16.02290" level=info msg="ETCD config not found, skip loading this plugin" loc="etcd/plugin_impl_etcd.go(272)" logger=etcd
time="2019-03-15 17:27:16.02295" level=info msg="Bolt config not found, skip loading this plugin" loc="bolt/plugin.go(111)" logger=bolt
time="2019-03-15 17:27:16.02302" level=info msg="kafka config not found  - skip loading this plugin" loc="kafka/plugin_impl_kafka.go(72)" logger=kafka
time="2019-03-15 17:27:16.82270" level=info msg="Connecting to VPP took 699.974853ms" loc="govppmux/plugin_impl_govppmux.go(147)" logger=govpp
time="2019-03-15 17:27:17.02236" level=info msg="VPP version: \"19.01-16~gd30202244-dirty\" (Mon Mar  4 19:44:38 UTC 2019)" loc="govppmux/plugin_impl_govppmux.go(335)" logger=govpp
time="2019-03-15 17:27:17.12266" level=info msg="VPP ACL plugin version: \"1.3\"" loc="govppmux/plugin_impl_govppmux.go(343)" logger=govpp
time="2019-03-15 17:27:17.12288" level=info msg="Plugin govpp: status check probe registered" loc="statuscheck/plugin_impl_statuscheck.go(137)" logger=status-check
time="2019-03-15 17:27:17.12293" level=info msg="Agent plugin state update." lastErr="<nil>" loc="statuscheck/plugin_impl_statuscheck.go(182)" logger=status-check plugin=govpp state=ok
time="2019-03-15 17:27:17.12385" level=info msg="Init Linux namespace handler" loc="linux/linuxplugin_init.go(203)" logger=linux
time="2019-03-15 17:27:17.62237" level=info msg="Namespace handler plugin initialized" loc="nsplugin/ns_handler.go(108)" logger=linux.ns-handler
time="2019-03-15 17:27:17.62250" level=info msg="Init Linux interface plugin" loc="linux/linuxplugin_init.go(213)" logger=linux
time="2019-03-15 17:27:17.62268" level=info msg="Linux interface configurator initialized" loc="ifplugin/interface_config.go(110)" logger=linux.if-conf
time="2019-03-15 17:27:17.62277" level=info msg="Init Linux L3 plugin" loc="linux/linuxplugin_init.go(238)" logger=linux
time="2019-03-15 17:27:17.62305" level=info msg="Resync strategy  is not known, setting up the full resync" loc="vpp/plugin_impl_vpp.go(409)" logger=vpp
time="2019-03-15 17:27:17.82234" level=info msg="VPP resync strategy is set to full" loc="vpp/plugin_impl_vpp.go(667)" logger=vpp
time="2019-03-15 17:27:17.82264" level=info msg="Init interface plugin" loc="vpp/plugin_impl_vpp.go(434)" logger=vpp
time="2019-03-15 17:27:17.92239" level=info msg="Initializing AF-Packet configurator" loc="ifplugin/afpacket_config.go(75)" logger=vpp.if-conf
time="2019-03-15 17:27:17.92254" level=info msg="Interface configurator initialized" loc="ifplugin/interface_config.go(110)" logger=vpp.if-conf
time="2019-03-15 17:27:17.92264" level=info msg="Interface state updater initialized" loc="ifplugin/interface_state.go(97)" logger=vpp.if-state
time="2019-03-15 17:27:17.92271" level=info msg=" BFD configurator initialized" loc="ifplugin/bfd_config.go(74)" logger=vpp.bfd-conf
time="2019-03-15 17:27:17.92276" level=info msg="STN configurator initialized" loc="ifplugin/stn_config.go(82)" logger=vpp.stn-conf
time="2019-03-15 17:27:17.92282" level=info msg="NAT configurator initialized" loc="ifplugin/nat_config.go(113)" logger=vpp.nat-conf
time="2019-03-15 17:27:17.92295" level=info msg="Init IPSec plugin" loc="vpp/plugin_impl_vpp.go(489)" logger=vpp
time="2019-03-15 17:27:17.92300" level=info msg="Init ACL plugin" loc="vpp/plugin_impl_vpp.go(502)" logger=vpp
time="2019-03-15 17:27:18.12228" level=warning msg="VPP health check probe timed out after 100ms (1. timeout)"
time="2019-03-15 17:27:18.12252" level=info msg="ACL configurator initialized" loc="aclplugin/acl_config.go(93)" logger=vpp.acl-plugin
time="2019-03-15 17:27:18.12260" level=info msg="Init L2 plugin" loc="vpp/plugin_impl_vpp.go(516)" logger=vpp
time="2019-03-15 17:27:18.12270" level=info msg="Initializing bridge domain state updater" loc="l2plugin/bd_state.go(93)" logger=vpp.l2-bd-state
time="2019-03-15 17:27:18.12278" level=info msg="L2 FIB configurator initialized" loc="l2plugin/fib_config.go(82)" logger=vpp.l2-fib-conf
time="2019-03-15 17:27:18.12291" level=info msg="L2 XConnect configurator initialized" loc="l2plugin/xconnect_config.go(65)" logger=vpp.xc-conf
time="2019-03-15 17:27:18.12295" level=info msg="Init L3 plugin" loc="vpp/plugin_impl_vpp.go(562)" logger=vpp
time="2019-03-15 17:27:18.12299" level=info msg="VPP ARP configurator initialized" loc="l3plugin/arp_config.go(79)" logger=vpp.l3-arp-conf
time="2019-03-15 17:27:18.12304" level=info msg="Proxy ARP configurator initialized" loc="l3plugin/arp_proxy_config.go(76)" logger=vpp.l3-proxy-arp-conf
time="2019-03-15 17:27:18.32259" level=info msg="Init L4 plugin" loc="vpp/plugin_impl_vpp.go(596)" logger=vpp
time="2019-03-15 17:27:18.32277" level=info msg="Init Punt plugin" loc="vpp/plugin_impl_vpp.go(609)" logger=vpp
time="2019-03-15 17:27:18.42361" level=info msg="Punt configurator initialized" loc="puntplugin/punt_config.go(58)" logger=vpp.punt-plugin
time="2019-03-15 17:27:18.52236" level=info msg="Init SR plugin" loc="vpp/plugin_impl_vpp.go(622)" logger=vpp
time="2019-03-15 17:27:18.62232" level=info msg="Segment routing configurator initialized" loc="srplugin/srv6_config.go(98)" logger=vpp.sr-plugin
time="2019-03-15 17:27:18.82244" level=info msg="Listening on http://0.0.0.0:9191" loc="rest/plugin_impl_rest.go(108)" logger=http
time="2019-03-15 17:27:18.82268" level=info msg="Resync order[]" loc="resync/plugin_impl_resync.go(105)" logger=resync
time="2019-03-15 17:27:18.82273" level=info msg="Resync took 97ns" durationInNs=97 loc="resync/plugin_impl_resync.go(122)" logger=resync
time="2019-03-15 17:27:18.92242" level=info msg="Plugin vpp: status check probe registered" loc="statuscheck/plugin_impl_statuscheck.go(137)" logger=status-check
time="2019-03-15 17:27:19.02228" level=info msg="HTTP not set, skip exposing GRPC services" loc="grpc/plugin_impl_grpc.go(82)" logger=grpc
time="2019-03-15 17:27:19.32271" level=info msg="Listening GRPC on: localhost:9111" loc="grpc/plugin_impl_grpc.go(90)" logger=grpc
time="2019-03-15 17:27:19.42258" level=info msg="VPP health check probe OK"
time="2019-03-15 17:27:19.52306" level=info msg="Starting health http-probe on port 9191" loc="probe/plugin_impl_probe.go(74)" logger=probe
time="2019-03-15 17:27:19.62249" level=info msg="Unable to register prometheus-probe handler, Prometheus is nil" loc="probe/plugin_impl_probe.go(86)" logger=probe
time="2019-03-15 17:27:19.62257" level=info msg="Serving /metrics on port 9191" loc="prometheus/plugin_impl_prometheus.go(87)" logger=prometheus
time="2019-03-15 17:27:19.62263" level=info msg="Serving /vpp on port 9191" loc="prometheus/plugin_impl_prometheus.go(87)" logger=prometheus
time="2019-03-15 17:27:19.62270" level=info msg="Resync order[]" loc="resync/plugin_impl_resync.go(105)" logger=resync
time="2019-03-15 17:27:19.62275" level=info msg="Resync took 101ns" durationInNs=101 loc="resync/plugin_impl_resync.go(122)" logger=resync
time="2019-03-15 17:27:19.62279" level=info msg="Agent started with 25 plugins (took 3.6s)" loc="agent/agent.go(168)" logger=agent
time="2019-03-15 17:27:26.72311" level=warning msg="VPP health check probe timing out, but some request on other channel was received 831.882µs ago, continue waiting!"
time="2019-03-15 17:27:29.12225" level=warning msg="VPP health check probe timed out after 100ms (1. timeout)"
time="2019-03-15 17:27:30.12327" level=info msg="VPP health check probe OK"
time="2019-03-15 17:27:46.62222" level=warning msg="VPP health check probe timed out after 100ms (1. timeout)"
time="2019-03-15 17:27:47.62278" level=info msg="VPP health check probe OK"
time="2019-03-15 17:27:50.22246" level=warning msg="VPP health check probe timed out after 100ms (1. timeout)"
time="2019-03-15 17:27:51.62228" level=error msg="Command failed: no reply received within the timeout period 1s" loc="telemetry/telemetry.go(393)" logger=telemetry
time="2019-03-15 17:27:52.12279" level=warning msg="VPP health check probe timed out after 100ms (2. timeout)"
time="2019-03-15 17:27:52.12291" level=error msg="VPP health check exceeded treshold for timeouts (>1), assuming disconnect"
time="2019-03-15 17:27:52.12340" level=info msg="Agent plugin state update." lastErr="VPP disconnected" loc="statuscheck/plugin_impl_statuscheck.go(182)" logger=status-check plugin=govpp state=error
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xcfd058]

goroutine 17 [running, locked to thread]:
github.com/ligato/vpp-agent/vendor/git.fd.io/govpp.git/adapter/vppapiclient.go_msg_callback(0xc000090352, 0x1300693c8, 0x110)
	/go/src/github.com/ligato/vpp-agent/vendor/git.fd.io/govpp.git/adapter/vppapiclient/vppapiclient.go:223 +0x58
github.com/ligato/vpp-agent/vendor/git.fd.io/govpp.git/adapter/vppapiclient._cgoexpwrap_4a4c415ed6b5_go_msg_callback(0x7f6d024d0352, 0x1300693c8, 0x110)
	_cgo_gotypes.go:472 +0x3f
```

**Comment by haiodo** [comment]
Issue is solved, by passing a proper request/limit to dataplane pod.
