### ISSUE TITLE
Runtime error when redploying nsmd

### ISSUE THREAD

**Issue by matrohon** [networkservicemesh/networkservicemesh#892]
## Steps to Reproduce

1. deploy nsm with "make k8s-infra-deploy"
2. redeploy it with the same command : sometime, nsmd is failing with the folowing panic error : 

## Failure Logs

```
k logs nsmgr-9fvvp nsmd 
time="2019-04-01T13:27:22Z" level=info msg="Using Jaeger host/port: 10.102.33.210:6831"
2019/04/01 13:27:22 Initializing logging reporter
time="2019-04-01T13:27:22Z" level=info msg="Requesting ClusterInfoClient..."
time="2019-04-01T13:27:22Z" level=info msg="Waiting for liveness probe: tcp:127.0.0.1:5000"
time="2019-04-01T13:27:22Z" level=info msg="Registry port now available, attempting to connect..."
time="2019-04-01T13:27:22Z" level=info msg="Successfully connected to 127.0.0.1:5000"
2019/04/01 13:27:22 Reporting span 51086b58bfc7a22c:51086b58bfc7a22c:0:1
time="2019-04-01T13:27:22Z" level=info msg="Starting NSM gRPC server listening on socket: /var/lib/networkservicemesh/nsm.io.sock"
time="2019-04-01T13:27:22Z" level=info msg="Requesting NsmRegistryClient..."
2019/04/01 13:27:22 Reporting span 16c793c2cc32fe9c:d7ea2ec52d382f7:16c793c2cc32fe9c:1
2019/04/01 13:27:22 Reporting span 37655880aac084a0:37655880aac084a0:0:1
2019/04/01 13:27:22 Reporting span 4f8d68477046dece:4f8d68477046dece:0:1
time="2019-04-01T13:27:22Z" level=error msg="failed to set local NSM Failed to get list of own Endpoints: rpc error: code = Unknown desc = no NetworkService with name: secure-intranet-connectivity"
time="2019-04-01T13:27:22Z" level=error msg="Error starting nsmd service: Failed to get list of own Endpoints: rpc error: code = Unknown desc = no NetworkService with name: secure-intranet-connectivity"k logs nsmgr-9fvvp nsmd 
time="2019-04-01T13:27:22Z" level=info msg="Using Jaeger host/port: 10.102.33.210:6831"
2019/04/01 13:27:22 Initializing logging reporter
time="2019-04-01T13:27:22Z" level=info msg="Requesting ClusterInfoClient..."
time="2019-04-01T13:27:22Z" level=info msg="Waiting for liveness probe: tcp:127.0.0.1:5000"
time="2019-04-01T13:27:22Z" level=info msg="Registry port now available, attempting to connect..."
time="2019-04-01T13:27:22Z" level=info msg="Successfully connected to 127.0.0.1:5000"
2019/04/01 13:27:22 Reporting span 51086b58bfc7a22c:51086b58bfc7a22c:0:1
time="2019-04-01T13:27:22Z" level=info msg="Starting NSM gRPC server listening on socket: /var/lib/networkservicemesh/nsm.io.sock"
time="2019-04-01T13:27:22Z" level=info msg="Requesting NsmRegistryClient..."
2019/04/01 13:27:22 Reporting span 16c793c2cc32fe9c:d7ea2ec52d382f7:16c793c2cc32fe9c:1
2019/04/01 13:27:22 Reporting span 37655880aac084a0:37655880aac084a0:0:1
2019/04/01 13:27:22 Reporting span 4f8d68477046dece:4f8d68477046dece:0:1
time="2019-04-01T13:27:22Z" level=error msg="failed to set local NSM Failed to get list of own Endpoints: rpc error: code = Unknown desc = no NetworkService with name: secure-intranet-connectivity"
time="2019-04-01T13:27:22Z" level=error msg="Error starting nsmd service: Failed to get list of own Endpoints: rpc error: code = Unknown desc = no NetworkService with name: secure-intranet-connectivity"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9171ef]

goroutine 1 [running]:
main.main()
	/root/networkservicemesh/controlplane/cmd/nsmd/nsmd.go:54 +0x58f
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9171ef]

goroutine 1 [running]:
main.main()
	/root/networkservicemesh/controlplane/cmd/nsmd/nsmd.go:54 +0x58f
```

**Comment by matrohon** [comment]
Additionally to the missing return statement that leads to a panic event, the root cause of the error is about nsmd looking for a ns named secure-intranet-connectivity that should have been delete with the previous "make k8s-vpn-delete" command.
