### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by lobkovilya** [networkservicemesh/networkservicemesh#901]
## Current Behavior
NSC in cycle create Request, ensures that it is established and Close it. Once in more than 1000 cases `fatal error: concurrent map iteration and map write` happens on remote NSM

## Failure Information (for bugs)
```go
func (srv *networkServiceManager) performNSERequest(requestId string, ctx context.Context, endpoint *registry.NSERegistration, requestConnection nsm.NSMConnection, request nsm.NSMRequest, dp *model.Dataplane, existingConnection *model.ClientConnection) (*model.ClientConnection, error) {

    ...

    logrus.Infof("NSM:(7.2.6.2-%v) Requesting NSE with request %v", requestId, message) 
    nseConnection, e := client.Request(ctx, message)

    ...

    // 7.2.6.2.4 update connection parameters, add workspace if local nse
    srv.updateConnectionParameters(requestId, nseConnection, endpoint)

    ...
}
```
Method `performNSERequest` call `Request` and receive `nseConnection` which is passed to `updateConnectionParameters` a bit later. According to logs `jaeger-client-go` calls `String()` on `nseConnection` while we update this struct in `updateConnectionParameters`.

## Failure Logs

```
fatal error: concurrent map iteration and map write

goroutine 4 [running]:
runtime.throw(0xac2ed5, 0x26)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000267190 sp=0xc000267160 pc=0x42c0a2
runtime.mapiternext(0xc0004ba720)
	/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc000267218 sp=0xc000267190 pc=0x40ec27
runtime.mapiterinit(0x9e61c0, 0xc000450840, 0xc0004ba720)
	/usr/local/go/src/runtime/map.go:850 +0x1c9 fp=0xc000267238 sp=0xc000267218 pc=0x40e599
reflect.mapiterinit(0x9e61c0, 0xc000450840, 0x0)
	/usr/local/go/src/runtime/map.go:1343 +0x54 fp=0xc000267268 sp=0xc000267238 pc=0x40fab4
reflect.Value.MapKeys(0x9e61c0, 0xc000450818, 0x195, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:1138 +0xc4 fp=0xc0002672e0 sp=0xc000267268 pc=0x4af254
github.com/golang/protobuf/proto.(*TextMarshaler).writeStruct(0xfb7024, 0xc0004e9d80, 0xa5f7c0, 0xc000450810, 0x199, 0x199, 0xb7af80)
	/go/pkg/mod/github.com/golang/protobuf@v1.3.1/proto/text.go:325 +0xc6d fp=0xc0002674c8 sp=0xc0002672e0 pc=0x59a9ad
github.com/golang/protobuf/proto.(*TextMarshaler).writeAny(0xfb7024, 0xc0004e9d80, 0xa8a1c0, 0xc0005607a0, 0x196, 0xc000462900, 0xb95200, 0xa8a1c0)
	/go/pkg/mod/github.com/golang/protobuf@v1.3.1/proto/text.go:534 +0x242 fp=0xc000267580 sp=0xc0002674c8 pc=0x59ba22
github.com/golang/protobuf/proto.(*TextMarshaler).writeStruct(0xfb7024, 0xc0004e9d80, 0xa7faa0, 0xc000560780, 0x199, 0x199, 0x7f0bb525c008)
	/go/pkg/mod/github.com/golang/protobuf@v1.3.1/proto/text.go:439 +0x875 fp=0xc000267768 sp=0xc000267580 pc=0x59a5b5
github.com/golang/protobuf/proto.(*TextMarshaler).Marshal(0xfb7024, 0xb7af80, 0xc0004508d0, 0xb86d20, 0xc000560780, 0xc000267880, 0xc000267880)
	/go/pkg/mod/github.com/golang/protobuf@v1.3.1/proto/text.go:809 +0x29b fp=0xc000267808 sp=0xc000267768 pc=0x59dbab
github.com/golang/protobuf/proto.(*TextMarshaler).Text(0xfb7024, 0xb86d20, 0xc000560780, 0x30, 0xc000267898)
	/go/pkg/mod/github.com/golang/protobuf@v1.3.1/proto/text.go:821 +0x6e fp=0xc000267858 sp=0xc000267808 pc=0x59dfee
github.com/golang/protobuf/proto.CompactTextString(...)
	/go/pkg/mod/github.com/golang/protobuf@v1.3.1/proto/text.go:843
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/apis/local/connection.(*Connection).String(0xc000560780, 0xad7948, 0xc0004498c0)
	/root/networkservicemesh/controlplane/pkg/apis/local/connection/connection.pb.go:171 +0x44 fp=0xc000267890 sp=0xc000267858 pc=0x8a1694
fmt.(*pp).handleMethods(0xc0004498c0, 0xc000000076, 0x84a001)
	/usr/local/go/src/fmt/print.go:616 +0x29b fp=0xc000267930 sp=0xc000267890 pc=0x4c88eb
fmt.(*pp).printArg(0xc0004498c0, 0xa8bf00, 0xc000560780, 0x76)
	/usr/local/go/src/fmt/print.go:699 +0x20a fp=0xc0002679c8 sp=0xc000267930 pc=0x4c8d6a
fmt.(*pp).doPrintf(0xc0004498c0, 0xaac1a4, 0x3, 0xc000267b58, 0x1, 0x1)
	/usr/local/go/src/fmt/print.go:1016 +0x158 fp=0xc000267ab0 sp=0xc0002679c8 pc=0x4cc768
fmt.Sprintf(0xaac1a4, 0x3, 0xc000267b58, 0x1, 0x1, 0xc0004e9d40, 0x16d)
	/usr/local/go/src/fmt/print.go:214 +0x66 fp=0xc000267b08 sp=0xc000267ab0 pc=0x4c5746
github.com/uber/jaeger-client-go.(*tags).EmitObject(0xc0004e9d60, 0xab28f2, 0xd, 0xa8bf00, 0xc000560780)
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.16.0+incompatible/jaeger_tag.go:78 +0x92 fp=0xc000267b78 sp=0xc000267b08 pc=0x87a8f2
github.com/opentracing/opentracing-go/log.Field.Marshal(0xab28f2, 0xd, 0xa, 0x0, 0x0, 0x0, 0xa8bf00, 0xc000560780, 0xb90480, 0xc0004e9d60)
	/go/pkg/mod/github.com/opentracing/opentracing-go@v1.1.0/log/field.go:223 +0x3cc fp=0xc000267bb8 sp=0xc000267b78 pc=0x83c99c
github.com/uber/jaeger-client-go.ConvertLogsToJaegerTags(0xc000482380, 0x1, 0x1, 0xc00000e698, 0x1, 0x1)
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.16.0+incompatible/jaeger_tag.go:31 +0x13c fp=0xc000267c70 sp=0xc000267bb8 pc=0x879a4c
github.com/uber/jaeger-client-go.buildLogs(0xc0005613e0, 0x2, 0x2, 0x100, 0xc0003efe70, 0x2)
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.16.0+incompatible/jaeger_thrift_span.go:80 +0x17a fp=0xc000267d78 sp=0xc000267c70 pc=0x87b50a
github.com/uber/jaeger-client-go.BuildJaegerThrift(0xc0001a05a0, 0x0)
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.16.0+incompatible/jaeger_thrift_span.go:42 +0x155 fp=0xc000267e28 sp=0xc000267d78 pc=0x87ac05
github.com/uber/jaeger-client-go.(*udpSender).Append(0xc00005e0c0, 0xc0001a05a0, 0x2, 0x1, 0x1)
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.16.0+incompatible/transport_udp.go:89 +0x42 fp=0xc000267ea0 sp=0xc000267e28 pc=0x888ae2
github.com/uber/jaeger-client-go.(*remoteReporter).processQueue(0xc0001280a0)
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.16.0+incompatible/reporter.go:273 +0x1eb fp=0xc000267fd8 sp=0xc000267ea0 pc=0x87f40b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000267fe0 sp=0xc000267fd8 pc=0x458461
created by github.com/uber/jaeger-client-go.NewRemoteReporter
	/go/pkg/mod/github.com/uber/jaeger-client-go@v2.16.0+incompatible/reporter.go:209 +0x146

...

goroutine 6715 [runnable]:
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).updateConnectionParameters(0xc0000867c0, 0xc0002298b8, 0x8, 0xb90380, 0xc000560780, 0xc0003cc4c0)
	/root/networkservicemesh/controlplane/pkg/nsm/nsm.go:574 +0x1b3
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).performNSERequest(0xc0000867c0, 0xc0002298b8, 0x8, 0xb895e0, 0xc0004500c0, 0xc0003cc4c0, 0xb90400, 0xc000474510, 0xb8ad20, 0xc000087ac0, ...)
	/root/networkservicemesh/controlplane/pkg/nsm/nsm.go:457 +0x73d
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).findConnectNSE(0xc0000867c0, 0xc0002298b8, 0x8, 0xb895e0, 0xc0004500c0, 0xc0002f7670, 0xb8ad20, 0xc000087ac0, 0xb90400, 0xc000558ab0, ...)
	/root/networkservicemesh/controlplane/pkg/nsm/nsm.go:322 +0x1f5
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).request(0xc0000867c0, 0xb895e0, 0xc0004500c0, 0xb8ad20, 0xc000087ac0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/networkservicemesh/controlplane/pkg/nsm/nsm.go:169 +0x6b1
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).Request(0xc0000867c0, 0xb895e0, 0xc0004500c0, 0xb8ad20, 0xc000087ac0, 0x1, 0x1, 0xb80de0, 0x325b82e686)
	/root/networkservicemesh/controlplane/pkg/nsm/nsm.go:67 +0x92
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/remote/network_service_server.(*remoteNetworkServiceServer).Request(0xc00005bb40, 0xb895e0, 0xc0004500c0, 0xc000087ac0, 0xc00005bb40, 0x0, 0x0)
	/root/networkservicemesh/controlplane/pkg/remote/network_service_server/remote_network_service_server.go:43 +0xf4
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/apis/remote/networkservice._NetworkService_Request_Handler.func1(0xb895e0, 0xc0004500c0, 0xa81f60, 0xc000087ac0, 0xa947c0, 0xc0001f40f0, 0xb895e0, 0xc0004500c0)
	/root/networkservicemesh/controlplane/pkg/apis/remote/networkservice/networkservice.pb.go:143 +0x86
github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0xb895e0, 0xc0002d7890, 0xa81f60, 0xc000087ac0, 0xc0004e93c0, 0xc0004e93e0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e4
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/apis/remote/networkservice._NetworkService_Request_Handler(0x9fa420, 0xc00005bb40, 0xb895e0, 0xc0002d7890, 0xc0003c2dc0, 0xc00035a2e0, 0xb895e0, 0xc0002d7890, 0xc0001d8510, 0x8c)
	/root/networkservicemesh/controlplane/pkg/apis/remote/networkservice/networkservice.pb.go:145 +0x158
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000356300, 0xb8f600, 0xc00047ac00, 0xc000122200, 0xc00025d830, 0xff04e0, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.19.1/server.go:971 +0x470
google.golang.org/grpc.(*Server).handleStream(0xc000356300, 0xb8f600, 0xc00047ac00, 0xc000122200, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.19.1/server.go:1250 +0xd25
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000452310, 0xc000356300, 0xb8f600, 0xc00047ac00, 0xc000122200)
	/go/pkg/mod/google.golang.org/grpc@v1.19.1/server.go:690 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.19.1/server.go:688 +0xa1

...
```

**Comment by lobkovilya** [comment]
Fix in progress

**Comment by nickolaev** [comment]
Merged. Closing.
