### ISSUE TITLE
nsmd crashes when playing with the vpn scenario

### ISSUE THREAD

**Issue by matrohon** [networkservicemesh/networkservicemesh#978]
## Current Behavior

After restarting nsmgr, nsmd is crashing and stays in CrashLoop state

## Failure Information (for bugs)

I was playing with restarts of vpn scenario components, crossconnect-monitor and nsmgr, and I had this trace which I cannot reproduce for now.

## Failure Logs

```
k logs -f nsmgr-xxzvk nsmd 
time="2019-04-18T14:02:56Z" level=info msg="Using Jaeger host/port: 10.103.123.125:6831"
2019/04/18 14:02:56 Initializing logging reporter
time="2019-04-18T14:02:56Z" level=info msg="Requesting ClusterInfoClient..."
time="2019-04-18T14:02:56Z" level=info msg="Registry port now available, attempting to connect..."
time="2019-04-18T14:02:56Z" level=info msg="Successfully connected to 127.0.0.1:5000"
2019/04/18 14:02:56 Reporting span 29afacd522af877b:29afacd522af877b:0:1
time="2019-04-18T14:02:56Z" level=info msg="Starting NSM gRPC server listening on socket: /var/lib/networkservicemesh/nsm.io.sock"
time="2019-04-18T14:02:56Z" level=info msg="Requesting NsmRegistryClient..."
2019/04/18 14:02:56 Reporting span 4d29f0f26928610:4d29f0f26928610:0:1
2019/04/18 14:02:56 Reporting span 10229c12bc087448:10229c12bc087448:0:1
time="2019-04-18T14:02:56Z" level=info msg="Setting local NSM name:\"kube-master\" url:\"10.32.0.6:5001\" last_seen:<seconds:1555596176 > state:\"RUNNING\" "
time="2019-04-18T14:02:56Z" level=info msg="Connecting to nsmd on socket: /var/lib/networkservicemesh/nsm.io.sock..."
time="2019-04-18T14:02:56Z" level=info msg="Requesting nsmd for client connection..."
time="2019-04-18T14:02:56Z" level=info msg="NSM gRPC socket: /var/lib/networkservicemesh/nsm.io.sock is operational"
time="2019-04-18T14:02:56Z" level=info msg="Values: [CLE nsm-18]"
time="2019-04-18T14:02:56Z" level=info msg="Values: [CLE nsm-7]"
time="2019-04-18T14:02:56Z" level=info msg="Values: [CLE nsm-19]"
time="2019-04-18T14:02:56Z" level=info msg="Clients: [nsm-18 nsm-7 nsm-19]"
time="2019-04-18T14:02:56Z" level=info msg="NSEs: map[]"
time="2019-04-18T14:02:56Z" level=info msg="NSMServer: Creating workspaces for existing clients..."
time="2019-04-18T14:02:56Z" level=info msg="Creating new workspace: nsm-18"
time="2019-04-18T14:02:56Z" level=info msg="Creating new directory: /var/lib/networkservicemesh/nsm-18"
time="2019-04-18T14:02:56Z" level=info msg="Creating new listener on: /var/lib/networkservicemesh/nsm-18/nsm.server.io.sock"
time="2019-04-18T14:02:56Z" level=info msg="Creating new NetworkServiceRegistryServer"
time="2019-04-18T14:02:56Z" level=info msg="Creating new MonitorConnectionServer"
time="2019-04-18T14:02:56Z" level=info msg="Creating new NetworkServiceServer"
time="2019-04-18T14:02:56Z" level=info msg="Creating new GRPC Server"
time="2019-04-18T14:02:56Z" level=info msg="Registering NetworkServiceRegistryServer with registerServer"
time="2019-04-18T14:02:56Z" level=info msg="Registering NetworkServiceServer with registerServer"
time="2019-04-18T14:02:56Z" level=info msg="Registering MonitorConnectionServer with registerServer"
time="2019-04-18T14:02:56Z" level=info msg="Serve starting..."
time="2019-04-18T14:02:56Z" level=info msg="grpcserver for workspace &{name:nsm-18 listener:0xc00000b4e0 registryServer:0xc00001dfb0 networkServiceServer:0xc0000595c0 monitorConnectionServer:0xc000236020 grpcServer:0xc000195380 Mutex:{state:0 sema:0} state:2 locationProvider:0xc000144240 localRegistry:0xc000134d00} is operational"
time="2019-04-18T14:02:56Z" level=info msg="Created new workspace: &{name:nsm-18 listener:0xc00000b4e0 registryServer:0xc00001dfb0 networkServiceServer:0xc0000595c0 monitorConnectionServer:0xc000236020 grpcServer:0xc000195380 Mutex:{state:0 sema:0} state:2 locationProvider:0xc000144240 localRegistry:0xc000134d00}"
time="2019-04-18T14:02:56Z" level=info msg="Creating new workspace: nsm-7"
time="2019-04-18T14:02:56Z" level=info msg="Creating new directory: /var/lib/networkservicemesh/nsm-7"
time="2019-04-18T14:02:56Z" level=info msg="Creating new listener on: /var/lib/networkservicemesh/nsm-7/nsm.server.io.sock"
time="2019-04-18T14:02:56Z" level=info msg="Creating new NetworkServiceRegistryServer"
time="2019-04-18T14:02:56Z" level=info msg="Creating new MonitorConnectionServer"
time="2019-04-18T14:02:56Z" level=info msg="Creating new NetworkServiceServer"
time="2019-04-18T14:02:56Z" level=info msg="Creating new GRPC Server"
time="2019-04-18T14:02:56Z" level=info msg="Registering NetworkServiceRegistryServer with registerServer"
time="2019-04-18T14:02:56Z" level=info msg="Registering NetworkServiceServer with registerServer"
time="2019-04-18T14:02:56Z" level=info msg="Registering MonitorConnectionServer with registerServer"
time="2019-04-18T14:02:56Z" level=info msg="Serve starting..."
time="2019-04-18T14:02:56Z" level=info msg="grpcserver for workspace &{name:nsm-7 listener:0xc00000bc80 registryServer:0xc000236810 networkServiceServer:0xc000059f40 monitorConnectionServer:0xc000236880 grpcServer:0xc000195e00 Mutex:{state:0 sema:0} state:2 locationProvider:0xc000144240 localRegistry:0xc000134d00} is operational"
time="2019-04-18T14:02:56Z" level=info msg="Created new workspace: &{name:nsm-7 listener:0xc00000bc80 registryServer:0xc000236810 networkServiceServer:0xc000059f40 monitorConnectionServer:0xc000236880 grpcServer:0xc000195e00 Mutex:{state:0 sema:0} state:2 locationProvider:0xc000144240 localRegistry:0xc000134d00}"
time="2019-04-18T14:02:56Z" level=info msg="Creating new workspace: nsm-19"
time="2019-04-18T14:02:56Z" level=info msg="Creating new directory: /var/lib/networkservicemesh/nsm-19"
time="2019-04-18T14:02:56Z" level=info msg="Creating new listener on: /var/lib/networkservicemesh/nsm-19/nsm.server.io.sock"
time="2019-04-18T14:02:56Z" level=info msg="Creating new NetworkServiceRegistryServer"
time="2019-04-18T14:02:56Z" level=info msg="Creating new MonitorConnectionServer"
time="2019-04-18T14:02:56Z" level=info msg="Creating new NetworkServiceServer"
time="2019-04-18T14:02:56Z" level=info msg="Creating new GRPC Server"
time="2019-04-18T14:02:56Z" level=info msg="Registering NetworkServiceRegistryServer with registerServer"
time="2019-04-18T14:02:56Z" level=info msg="Registering NetworkServiceServer with registerServer"
time="2019-04-18T14:02:56Z" level=info msg="Registering MonitorConnectionServer with registerServer"
time="2019-04-18T14:02:56Z" level=info msg="Serve starting..."
time="2019-04-18T14:02:56Z" level=info msg="grpcserver for workspace &{name:nsm-19 listener:0xc00028c440 registryServer:0xc000237060 networkServiceServer:0xc000288840 monitorConnectionServer:0xc0002370d0 grpcServer:0xc0002a6480 Mutex:{state:0 sema:0} state:2 locationProvider:0xc000144240 localRegistry:0xc000134d00} is operational"
time="2019-04-18T14:02:56Z" level=info msg="Created new workspace: &{name:nsm-19 listener:0xc00028c440 registryServer:0xc000237060 networkServiceServer:0xc000288840 monitorConnectionServer:0xc0002370d0 grpcServer:0xc0002a6480 Mutex:{state:0 sema:0} state:2 locationProvider:0xc000144240 localRegistry:0xc000134d00}"
time="2019-04-18T14:02:56Z" level=info msg="Requesting NseRegistryClient..."
time="2019-04-18T14:02:56Z" level=info msg="NSMD: Restore of NSE/Clients Complete..."
time="2019-04-18T14:02:56Z" level=info msg="Starting Dataplane registration server..."
time="2019-04-18T14:02:56Z" level=info msg="Serve starting..."
time="2019-04-18T14:02:56Z" level=info msg="Serve starting..."
time="2019-04-18T14:02:56Z" level=info msg="Starting Dataplane Registrar gRPC server listening on socket: /var/lib/networkservicemesh/nsm.dataplane-registrar.io.sock"
time="2019-04-18T14:02:56Z" level=info msg="dataplane registrar Server socket: /var/lib/networkservicemesh/nsm.dataplane-registrar.io.sock is operational"
time="2019-04-18T14:02:56Z" level=info msg="Waiting for dataplane available..."
time="2019-04-18T14:02:56Z" level=info msg="Received new dataplane registration requests from vppagent"
time="2019-04-18T14:02:56Z" level=info msg="Dataplane added: &{vppagent /var/lib/networkservicemesh/nsm-vppagent.dataplane.sock [] []}"
time="2019-04-18T14:02:56Z" level=info msg="Starting Dataplane crossconnect monitoring client..."
2019/04/18 14:02:56 Reporting span 3fb583f66b4fdca8:68c5bd745d0a78a1:3fb583f66b4fdca8:1
time="2019-04-18T14:02:56Z" level=info msg="Connecting to Dataplane vppagent /var/lib/networkservicemesh/nsm-vppagent.dataplane.sock"
time="2019-04-18T14:02:56Z" level=info msg="Liveness Request received"
time="2019-04-18T14:02:56Z" level=info msg="Monitoring vppagent CrossConnections..."
time="2019-04-18T14:02:56Z" level=info msg="Dataplane vppagent informed of its parameters changes, applying new parameters [type:VXLAN parameters:<key:\"src_ip\" value:\"172.28.128.16\" > ]"
time="2019-04-18T14:02:56Z" level=info msg="Receive event from dataplane vppagent: INITIAL_STATE_TRANSFER map[3:id:\"3\" payload:\"IP\" local_source:<id:\"3\" network_service:\"secure-intranet-connectivity\" mechanism:<type:MEM_INTERFACE parameters:<key:\"description\" value:\"Describe 2\" > parameters:<key:\"name\" value:\"2\" > parameters:<key:\"netnsInode\" value:\"4026532975\" > parameters:<key:\"socketfile\" value:\"2/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-18\" > > context:<src_ip_addr:\"10.60.1.1/30\" dst_ip_addr:\"10.60.1.2/30\" src_ip_required:true dst_ip_required:true routes:<prefix:\"8.8.8.8/30\" > excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" ip_neighbors:<ip:\"10.32.0.10\" hardware_address:\"f2:b9:4f:b1:15:2a\" > > labels:<key:\"app\" value:\"firewall\" > state:DOWN > local_destination:<id:\"4\" network_service:\"secure-intranet-connectivity\" mechanism:<type:KERNEL_INTERFACE parameters:<key:\"description\" value:\"NSM Endpoint\" > parameters:<key:\"name\" value:\"nsmajp7qeRo\" > parameters:<key:\"netnsInode\" value:\"4026533045\" > parameters:<key:\"socketfile\" value:\"nsmajp7qeRo/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-7\" > parameters:<key:\"workspaceNseName\" value:\"secure-intranet-connectivitywckzx\" > > context:<src_ip_addr:\"10.60.1.1/30\" dst_ip_addr:\"10.60.1.2/30\" src_ip_required:true dst_ip_required:true routes:<prefix:\"8.8.8.8/30\" > excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" ip_neighbors:<ip:\"10.32.0.10\" hardware_address:\"f2:b9:4f:b1:15:2a\" > > state:DOWN >  1:id:\"1\" payload:\"IP\" local_source:<id:\"1\" network_service:\"secure-intranet-connectivity\" mechanism:<type:KERNEL_INTERFACE parameters:<key:\"description\" value:\"Primary interface\" > parameters:<key:\"name\" value:\"nsm\" > parameters:<key:\"netnsInode\" value:\"4026533123\" > parameters:<key:\"socketfile\" value:\"nsm/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-19\" > > context:<src_ip_addr:\"10.60.1.1/30\" dst_ip_addr:\"10.60.1.2/30\" src_ip_required:true dst_ip_required:true routes:<prefix:\"8.8.8.8/30\" > excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" ip_neighbors:<ip:\"10.32.0.10\" hardware_address:\"f2:b9:4f:b1:15:2a\" > > labels:<key:\"\" value:\"\" > state:DOWN > local_destination:<id:\"2\" network_service:\"secure-intranet-connectivity\" mechanism:<type:MEM_INTERFACE parameters:<key:\"description\" value:\"NSM Endpoint\" > parameters:<key:\"name\" value:\"nsmkQgFzs5oe\" > parameters:<key:\"netnsInode\" value:\"4026532975\" > parameters:<key:\"socketfile\" value:\"nsmkQgFzs5oe/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-18\" > parameters:<key:\"workspaceNseName\" value:\"secure-intranet-connectivityhnrnt\" > > context:<src_ip_addr:\"10.60.1.1/30\" dst_ip_addr:\"10.60.1.2/30\" src_ip_required:true dst_ip_required:true routes:<prefix:\"8.8.8.8/30\" > excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" ip_neighbors:<ip:\"10.32.0.10\" hardware_address:\"f2:b9:4f:b1:15:2a\" > > state:DOWN > ]"
time="2019-04-18T14:02:56Z" level=info msg="Restoring state of active connection id:\"3\" payload:\"IP\" local_source:<id:\"3\" network_service:\"secure-intranet-connectivity\" mechanism:<type:MEM_INTERFACE parameters:<key:\"description\" value:\"Describe 2\" > parameters:<key:\"name\" value:\"2\" > parameters:<key:\"netnsInode\" value:\"4026532975\" > parameters:<key:\"socketfile\" value:\"2/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-18\" > > context:<src_ip_addr:\"10.60.1.1/30\" dst_ip_addr:\"10.60.1.2/30\" src_ip_required:true dst_ip_required:true routes:<prefix:\"8.8.8.8/30\" > excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" ip_neighbors:<ip:\"10.32.0.10\" hardware_address:\"f2:b9:4f:b1:15:2a\" > > labels:<key:\"app\" value:\"firewall\" > state:DOWN > local_destination:<id:\"4\" network_service:\"secure-intranet-connectivity\" mechanism:<type:KERNEL_INTERFACE parameters:<key:\"description\" value:\"NSM Endpoint\" > parameters:<key:\"name\" value:\"nsmajp7qeRo\" > parameters:<key:\"netnsInode\" value:\"4026533045\" > parameters:<key:\"socketfile\" value:\"nsmajp7qeRo/memif.sock\" > parameters:<key:\"workspace\" value:\"nsm-7\" > parameters:<key:\"workspaceNseName\" value:\"secure-intranet-connectivitywckzx\" > > context:<src_ip_addr:\"10.60.1.1/30\" dst_ip_addr:\"10.60.1.2/30\" src_ip_required:true dst_ip_required:true routes:<prefix:\"8.8.8.8/30\" > excluded_prefixes:\"10.32.0.0/12\" excluded_prefixes:\"10.96.0.0/12\" ip_neighbors:<ip:\"10.32.0.10\" hardware_address:\"f2:b9:4f:b1:15:2a\" > > state:DOWN > "
time="2019-04-18T14:02:56Z" level=info msg="Requesting NetworkServiceDiscoveryClient..."
time="2019-04-18T14:02:56Z" level=info msg="Discovering endpoint at registry Network service: secure-intranet-connectivity endpoint: secure-intranet-connectivitywckzx "
2019/04/18 14:02:56 Reporting span 6f8c8288b058df32:6f8c8288b058df32:0:1
time="2019-04-18T14:02:56Z" level=error msg="Failed to find NSE to recovery: rpc error: code = Unknown desc = no NetworkService with name: secure-intranet-connectivity"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x88b215]

goroutine 73 [running]:
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsm.(*networkServiceManager).RestoreConnections(0xc0001386c0, 0xc0003ea530, 0x2, 0x2, 0xc000029558, 0x8)
	/root/networkservicemesh/controlplane/pkg/nsm/nsm.go:766 +0xc85
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/services.(*ClientConnectionManager).UpdateFromInitialState(0xc0001e21e0, 0xc0003ea530, 0x2, 0x2, 0xc0002e2780)
	/root/networkservicemesh/controlplane/pkg/services/client_connection_manager.go:174 +0x68
github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsmd.(*NsmMonitorCrossConnectClient).dataplaneCrossConnectMonitor(0xc0001e2270, 0xc0002e2780, 0xb06860, 0xc000289540)
	/root/networkservicemesh/controlplane/pkg/nsmd/nsmd_crossconnect_client.go:198 +0x9c0
created by github.com/networkservicemesh/networkservicemesh/controlplane/pkg/nsmd.(*NsmMonitorCrossConnectClient).DataplaneAdded
	/root/networkservicemesh/controlplane/pkg/nsmd/nsmd_crossconnect_client.go:83 +0x111
```

**Comment by nickolaev** [comment]
So we have `VPP 2.0.2` integrated now. That should be fixed. Please retest with `master`.

**Comment by matrohon** [comment]
I didn't see this bug happening for a while, it seems fixed
